package:
  name: visualizer
  version: "0.1.0"

source:
  path: .

requirements:
  build:
    - setuptools
    - pyqt>=5
    - clingo
    - python>=3
  run:
    - pyqt>=5
    - clingo
    - python>=3

test:
  imports:
    - visualizer

about:
  home: https://github.com/potassco/asprilo/tree/develop/visualizer
  summary: "A tool to visualize asprilo problems"
